version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:11.3
    hostname: postgres-richard
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./volumes/postgresql-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
